version: '3.9'
services:

  redis:
    image: redis
    restart: always
    volumes:
      - /srv/beme/redis:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "85:85"
    environment:
      ENV: PRODUCTION
      SECRET_KEY: 'frtA-PIk4qFOf15TUNW-EIYfgaaqM_SpG5nxTX4Pyqk='
      REDIS_HOST: redis
      MEDIANA_KEY: 'xxx'
    depends_on:
      redis:
        condition: service_started
