"""
beme Project (Generated by Panther on 2024-01-05)
"""
import os
from pathlib import Path

from panther.utils import load_env

BASE_DIR = Path(__name__).resolve().parent
if os.environ.get('ENV') != 'PRODUCTION':
    load_env(BASE_DIR / ".env")

SECRET_KEY = os.environ["SECRET_KEY"]
MEDIANA_KEY = os.environ["MEDIANA_KEY"]
REDIS_HOST = os.environ["REDIS_HOST"]

OTP_LEN = 4
OTP_EXP_SECOND = 90

MIDDLEWARES = [
    (
        "panther.middlewares.db.DatabaseMiddleware",
        {"url": f"pantherdb://{BASE_DIR}/database.pdb"},
    ),
    (
        "panther.middlewares.redis.RedisMiddleware", {'host': REDIS_HOST},
    ),
]

USER_MODEL = "user.models.User"

AUTHENTICATION = "panther.authentications.JWTAuthentication"

MONITORING = True

LOG_QUERIES = True

URLs = "core.urls.url_routing"

PANTHERDB_ENCRYPTION = False
